---
- name: Message Discord de début de role.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Démarrage de l'installation de la partie commune."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Installation des dépôts debian 11
  template:
    src: templates/sourcelist.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Mise à jour de la VM."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Mise à jour de la VM.
  apt:
    name: "*"
    state: latest

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Installation des packages du rôle."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"


- name: Gestion d'erreur lors de l'installation des packages du role.
  block:
    - name: Installation des packages du rôle.
      apt:
        name: "{{ liste_install }}"
        state: latest
        update_cache: yes
        dpkg_options: Dpkg::Options::="--force-overwrite" --fix-broken install
  rescue:
    - name: Installation du script.
      template:
        src: templates/script_install.j2
        dest: /root/script_install.sh
        owner: root
        group: root
        mode: 0700

    - name: Exécution du script d'installation.
      shell: /root/script_install.sh
      args:
        executable: /bin/bash

    - name: Suppression du script d'installation.
      file:
        path: /root/script_install.sh
        state: absent

- name: Mise à jour des packages de bases python.
  pip:
    name: "{{ liste_pip }}"
    executable: pip3
    state: latest

- name: Arret de chrony.
  systemd:
    name: chrony
    state: stopped
    enabled: yes

- name: Configuration de chrony.
  template:
    src: templates/chrony.j2
    dest: /etc/chrony.conf
    backup: no
    owner: root
    group: root
    mode: 0644

- name: Redémarrage de chrony.
  systemd:
    name: chrony
    state: started
    enabled: yes

- name: Ouverture d'un port pour le service chrony.
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
    immediate: yes

- name: Suppression du motd cockpit.
  file:
    path: /etc/motd.d/cockpit
    state: absent

- name: Vérification du démarrage de cockpit.
  systemd:
    name: cockpit
    state: started
    enabled: yes

- name: Ouverture d'un port pour le service cockpit.
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled
    immediate: yes

- name: Ouverture d'un port pour les services web.
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - http
    - https

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "ATTENTION !! Le serveur de jeux est en cours de redémarrage."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Message Discord de fin de role.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    embeds:
      - title: "Serveur redémarré avec succès."
        description: |
           "Le serveur a été redémarré avec succès.
           "Tu peux reprendre une vie normale."
           "Et moi, je continue mon boulot."
        footer:
          text: "Author: Ansible"
        image:
          avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"
