---
- name: Installation et configuration de la machine.
  hosts: serveur
  remote_user: root
  gather_facts: yes
  roles:
    - configuration
    - tronccommun
    - durcissement
    - monit
    - steam
