---
- name: "Mise à jour du système."
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Installation des packages du role.
  apt:
    name: "{{ liste_install }}"
    state: latest

- name: Ajout d'une règle dans le pare-feu pour monit.
  firewalld:
    port: "{{ port_ecoute }}/tcp"
    permanent: True
    state: enabled
    immediate: yes

- name: Arret du service monit.
  systemd:
    name: monit
    state: stopped
    enabled: yes
