---
- name: Message Discord de début de role.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Démarrage de la configuration du serveur."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Installation des dépôts debian.
  template:
    src: templates/sourcelist.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Ajout de dépots tiers.
  template:
    src: "templates/{{ item. source }}"
    dest: "/etc/apt/sources.list.d/{{ item. destination }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - { source: 'backports.j2', destination: 'backports.list' }

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Installation des packages."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Installation des packages du rôle.
  apt:
    name: "{{ liste_install }}"
    state: latest
    update_cache: yes

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Installation des packages terminé."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Ajout de la résolution du nom du serveur.
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }}  {{ fqdn_machine | lower }} {{ nom | lower }}"
    insertafter: 'EOF'
    state: present
    owner: root
    group: root
    mode: 0644
    backup: no

- name: Configuration de la timezone.
  timezone:
    name: Europe/Paris

- name: Copie du script de config de la machine.
  template:
    src: templates/configmachine.j2
    dest: /root/configmachine.sh
    backup: no
    owner: root
    group: root
    mode: 0700

- name: Execution du script de config.
  shell: ./configmachine.sh
  args:
    chdir: /root/
    executable: /bin/bash
  register: var_config
  failed_when: var_config.rc != 0
  changed_when: var_config.rc == 0

- name: Suppression du script de config.
  file:
    path: /root/configmachine.sh
    state: absent

- name: Création des répertoires pour les alias.
  file:
    path: "{{ item.chemin }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { chemin: '/root/.alias', mode: '0755' }
    - { chemin: '/etc/skel/.alias', mode: '0755' }

- name: Copie des templates d'alias.
  template:
    src: "templates/{{ item.fichier }}"
    dest: "{{ item.chemin }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  with_items:
    - { fichier: 'alias_utilisateur.j2', chemin: '/etc/skel/.alias/alias.txt' }
    - { fichier: 'alias_root.j2', chemin: '/root/.alias/alias.txt' }

- name: Copie de la banniére.
  copy:
    src: files/baniere.txt
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - '/etc/skel/.alias/banniere.txt'
    - '/root/.alias/banniere.txt'

- name: Ajout d'une référence dans le fichier bashrc.
  lineinfile:
    path: "{{ item }}/.bashrc"
    line: 'source ~/.alias/alias.txt'
    owner: root
    group: root
    mode: 0644
    insertafter: EOF
    state: present
    backup: no
  with_items:
    - /etc/skel
    - /root

- name: Suppression de l'ancienne clé SSH sur la machine locale.
  shell: 'sed -i "/{{ ansible_default_ipv4.address }}/d" $HOME/.ssh/known_hosts'
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: var_sshkey
  failed_when: var_sshkey.rc != 0
  changed_when: var_sshkey.rc == 0

- name: Message Discord de fin de role.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Configuration du serveur terminé."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"
