---
- name: Message Discord de début de role.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Démarrage du durcissement du système."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Augmentation de la sécurité des mots de passe.
  lineinfile:
    path: /etc/pam.d/passwd
    line: "password   required     pam_unix.so sha512 shadow nullok rounds=65536"
    owner: root
    group: root
    mode: '0644'
    state: present
    backup: no

- name: Modification de la variable umask et de la méthode de chiffrement.
  lineinfile:
    path: /etc/login.defs
    regexp: "{{ item.regex }}"
    line: "{{ item.ligne }}"
    owner: root
    group: root
    mode: '0644'
    state: present
  with_items:
    - { regex: '^UMASK', ligne: 'UMASK           027' }
    - { regex: '^ENCRYPT_METHOD', ligne: 'ENCRYPT_METHOD SHA512' }

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Mise à jour du mot de passe root."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Mise à jour du mot de passe root.
  user:
    name: root
    state: present
    password: "{{ new_passwd | password_hash('sha512', 'SebAsTuX') }}"
    update_password: always

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Retrait de la nouvelle clé chez le serrurier."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Création d'une clé ssh pour le compte root.
  openssh_keypair:
    path: "../cles_ssh/root"
    backend: cryptography
    comment: "Clé SSH généré par ansible."
    mode: 0600
    regenerate: always
    state: present
    type: ed25519
  delegate_to: localhost

- name: Installation de la clé sur le compte.
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '../cles_ssh/root.pub') }}"
    comment: "Clé SSH généré et installé par ansible."
    exclusive: yes
    manage_dir: yes

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Installation des packages du rôle."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Installation des packages du rôle.
  apt:
    name: "{{ liste_install }}"
    state: latest
    update_cache: yes

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Démarrage du pare-feu et ouverture / fermeture de ports, Attention les doigts ça brule."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"


- name: Gestion de services.
  block:
    - name: Démarrage de fail2ban.
      systemd:
        name: fail2ban
        state: stopped
        enabled: no

    - name: Arret du service apache.
      systemd:
        name: apache2
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Démarrage du pare-feu.
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Arret d'apparmor.
      systemd:
        name: apparmor
        state: stopped
        enabled: no

- name: Gestion du pare feu.
  block:
    - name: Ouverture du port cockpit.
      firewalld:
        service: cockpit
        permanent: yes
        immediate: yes
        state: enabled

    - name: Fermeture de ports inutile.
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      with_items:
        - http
        - https
        - ftp

- name: Gestion du SSH.
  block:
    - name: Installation du fichier de configuration du ssh original.
      template:
        src: templates/sshd_config_orig.j2
        dest: /etc/ssh/sshd_config
        backup: no
        owner: root
        group: root
        mode: 0644

    - name: Installation du fichier de configuration du ssh modifié.
      template:
        src: templates/sshd_config_modif.j2
        dest: /etc/ssh/sshd_config.d/sshd_ansible.conf
        backup: no
        owner: root
        group: root
        mode: 0644

    - name: Suppression du port SSH par défaut.
      firewalld:
        service: ssh
        permanent: yes
        state: disabled
        immediate: no

    - name: Ouverture du nouveau port SSH.
      firewalld:
        port: "{{ new_ssh_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: no

- name: Suppression de la mise à jour du motd.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/update-motd.d/10-uname
    - /etc/issue.d/cockpit.issue
    - /etc/motd.d/cockpit

- name: Ajout d’adresse IP en liste blanche du pare feu.
  firewalld:
    source: "{{ ip_whitelist }}"
    state: enabled
    permanent: yes

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Désactivation diverse et blaclistage en cours. T'inquiète t'es pas encore concerné :D ."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Désactivation et blacklistage.
  block:
    - name: Désactivation du protocole dccp - blacklist.
      kernel_blacklist:
        name: dccp
        state: present

    - name: Désactivation du protocole dccp - modprobe.
      lineinfile:
        dest: /etc/modprobe.d/no-dccp.conf
        line: 'blacklist dccp'
        mode: '0644'
        create: yes

    - name: Désactivation du protocole sctp - blacklist.
      kernel_blacklist:
        name: sctp
        state: present

    - name: Désactivation du sctp - modprobe.
      lineinfile:
        dest: /etc/modprobe.d/no-sctp.conf
        line: 'blacklist sctp'
        mode: '0644'
        create: yes

    - name: Désactivation du protocole rds - blacklist.
      kernel_blacklist:
        name: rds
        state: present

    - name: Désactivation du rds - modprobe.
      lineinfile:
        dest: /etc/modprobe.d/no-rds.conf
        line: 'blacklist rds'
        mode: '0644'
        create: yes

    - name: Désactivation du protocole tipc - blacklist.
      kernel_blacklist:
        name: tipc
        state: present

    - name: Désactivation du tipc - modprobe.
      lineinfile:
        dest: /etc/modprobe.d/no-tipc.conf
        line: 'blacklist tipc'
        mode: '0644'
        create: yes

    - name: Désactivation des ports USB - blacklist.
      kernel_blacklist:
        name: usb-storage
        state: present

    - name: Désactivation des ports USB - modprobe.
      lineinfile:
        dest: /etc/modprobe.d/no-usb.conf
        line: 'install usb-storage /bin/true'
        mode: '0644'
        create: yes

    - name: Désactivation du firewire - blacklist.
      kernel_blacklist:
        name: firewire-core
        state: present

    - name: Désactivation du firewire - modprobe.
      lineinfile:
        dest: /etc/modprobe.d/no-firewire.conf
        line: "{{ item }}"
        mode: '0644'
        create: yes
      with_items:
        - 'blacklist ohci1394'
        - 'blacklist sbp2'
        - 'blacklist dv1394'
        - 'blacklist raw1394'
        - 'blacklist video1394'
        - 'blacklist firewire-ohci'
        - 'blacklist firewire-sbp2'

    - name: Modification de certaines limites du système.
      template:
        src: templates/conf_limit.j2
        dest: /etc/security/limits.d/conf_limit.conf
        backup: no
        owner: root
        group: root
        mode: 0644

- name: Installation des fichiers de configuration de fail2ban.
  template:
    src: "templates/{{ item.source }}"
    dest: "/etc/fail2ban/{{ item.destination }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  with_items:
    - { source: 'jail.j2', destination: 'jail.conf' }
    - { source: 'fail2ban_jail_conf.j2', destination: 'jail.local' }
    - { source: 'sshd_f2b.j2', destination: 'fail2ban.d/sshd.conf' }

- name: Message Discord de début de playbook.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "ATTENTION !! Le serveur de jeux est en cours de redémarrage."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Suppression de l'ancienne clé SSH sur la machine locale.
  shell: 'sed -i "/{{ ansible_default_ipv4.address }}/d" $HOME/.ssh/known_hosts'
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: var_sshkey
  failed_when: var_sshkey.rc != 0
  changed_when: var_sshkey.rc == 0

- name: Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 60
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  ignore_errors: True

- name: Mise à jour du port SSH.
  set_fact:
    ansible_port: "{{ new_ssh_port }}"

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Le système est maintenant bien dur."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"
