---
- name: Modification d'un utillisateur.
  hosts: serveur
  gather_facts: yes
  vars_prompt:

    - name: login
      prompt: "Veuillez entrer l'identifiant du compte "
      private: no

    - name: password
      prompt: "Veuillez entrer le mot de passe du compte utilisateur "
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
      default: "P@ssW0rD01"

  tasks:
    - name: "Modification du mot de passe du compte : {{ login }}"
      user:
        name: "{{ login }}"
        password: "{{ password }}"
        state: present
        update_password: always

    - name: Message Discord de fin de playbook.
      community.general.discord:
        webhook_id: "{{ id_webhook }}"
        webhook_token: "{{ token_webhook }}"
        embeds:
          - title: "Compte {{ login }} modifié avec succés"
            description: |
               "Mot de passe : Non je déconne, t'auras pas le nouveau non plus. :D"
            footer:
              text: "Author: Ansible"
            image:
              avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"
