---
- name: Redémarrage du serveur.
  hosts: serveur
  gather_facts: yes
  tasks:
    - name: Message Discord de début de playbook.
      community.general.discord:
        webhook_id: "{{ id_webhook }}"
        webhook_token: "{{ token_webhook }}"
        content: "ATTENTION !! Le serveur de jeux est en cours de redémarrage."
        username: Ansible
        avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

    - name: Redémarrage du serveur.
      reboot:
        msg: "Redémarrage automatique du serveur par ansible."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime

    - name: Message Discord de fin de playbook.
      community.general.discord:
        webhook_id: "{{ id_webhook }}"
        webhook_token: "{{ token_webhook }}"
        embeds:
          - title: "Serveur redémarré avec succès.
            description: |
               "Le serveur a été redémarré avec succès.
               "Tu peux reprendre une vie normale."
            footer:
              text: "Author: Ansible"
            image:
              avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"
