---
liste_install: [ 'monit', 'lm-sensors', 'sysstat', 'wget', 'rrdtool',
                 'firewalld', 'aptitude', 'iftop', 'iotop', 'itop',
                 'htop', 'zlib1g-dev', 'libpam0g-dev', 'libssl-dev',
                 'libtool', 'bison', 'flex', 'autoconf', 'build-essential',
                 'make' ]


# ************* Configuration de monit *************

# Identifiant du compte admin de l'interface web monit
cpte_admin: "{{ admin_monit }}"

# Mot de passe du compte admin permettant l'accès à l'interface web
mdp_admin: "{{ admin_passwd }}"

# Identifiant du compte utilisateur permettant l'accès à l'interface web
cpte_utils: "{{ user_monit }}"

# Mot de passe du compte utilisateur permettant l'accès à l'interface web
mdp_utils: "{{ user_passwd }}"

# Configuration du port d'écoute permettant l'accès à l'interface web.
port_ecoute: "{{ port_monit | default('2812') }}"

# Autoriser l'utilisation du compte invité en lecture seule. Les valeurs sont true ou false
autorisation_guest: "{{ activate_user | bool }}"

# Autoriser l'accès en local. Les valeurs sont true ou false
autorisation_localhost: false

# Utiliser ou pas le ssl pour l'interface web. Valeur enable ou disable.
ssl_enable: "{{ activate_ssl | bool }}"

temps_demarrage: 10
temps_sureveillance: 15

version_monit: "5.32.0"
