---
- name: Message Discord de début de role.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Démarrage de l'installation de monitorix."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Mise à jour du système.
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Installation des packages du rôle."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Installation des packages du rôle.
  apt:
    name: "{{ liste_install }}"
    state: latest

- name: Arrêt du service monitorix.
  systemd:
    name: monitorix
    state: stopped
    enabled: no

- name: Installation du fichier de configuration de monitorix.
  template:
    src: templates/monitorixconf.j2
    dest: /etc/monitorix/monitorix.conf
    owner: root
    group: root
    mode: 0644
    backup: no

- name: Ajout d'une règle dans le pare-feu.
  firewalld:
    port: "{{ port_monitorix }}/tcp"
    permanent: True
    state: enabled
    immediate: yes

- name: Démarrage du service monitorix.
  systemd:
    name: monitorix
    state: started
    enabled: yes

- name: Message Discord de fin de rôle.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Monitorix a été installée avec succès."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"
