---
- name: Installation des dépôts debian.
  template:
    src: templates/sourcelist.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Ajout de dépots tiers.
  template:
    src: "templates/{{ item. source }}"
    dest: "/etc/apt/sources.list.d/{{ item. destination }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - {source: 'backports.j2', destination: '' }
    - {source: 'proposedupdate.j2', destination: '' }

- name: Ajout de la résolution du nom du serveur.
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }}  {{ fqdn_serveur }} {{ hostname }}"
    insertafter: '^127\.0\.0\.1'
    state: present
    owner: root
    group: root
    mode: 0644
    backup: no

- name: Mise à jour de la VM.
  apt:
    name: "*"
    state: latest

- name: Installation des packages du rôle.
  apt:
    name: "{{ liste_install }}"
    state: latest
    update_cache: yes

- name: Mise à jour des packages de bases python.
  pip:
    name: "{{ liste_pip }}"
    executable: pip3
    state: latest

- name: Configuration de la timezone.
  community.general.timezone:
    name: Europe/Paris

- name: Configuration du ssh.
  template:
    src: "templates/{{ item.fichier }}"
    dest: "{{ item.chemin }}"
    backup: "{{ item.sauve }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { fichier: 'sshd_config_orig.j2', chemin: '/etc/ssh/sshd_config', sauve: 'no' }
    - { fichier: 'sshd_config_modif.j2', chemin: '/etc/ssh/sshd_config.d/01-sshd_ansible.conf', sauve: 'no' }

- name: Création des répertoires pour les alias.
  file:
    path: "{{ item.chemin }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - {chemin: '/root/.alias', mode: '0644' }
    - {chemin: '/etc/skel/.alias', mode: '0755' }

- name: Copie des templates d'alias.
  template:
    src: "templates/{{ item.fichier }}"
    dest: "{{ item.chemin }}"
    backup: "{{ item.sauve }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { fichier: 'alias_utilisateur.j2', chemin: '/etc/skel/.alias/alias.txt', sauve: 'no' }
    - { fichier: 'alias_root.j2', chemin: '/root/.alias/alias.txt', sauve: 'no' }

- name: Ajout d'une référence dans le fichier bashrc.
  lineinfile:
    path: "{{ item }}/.bashrc"
    line: 'source ~/.alias/alias.txt'
    owner: root
    group: root
    mode: 0644
    insertafter: EOF
    state: present
    backup: no
  with_items:
    - /etc/skel
    - /root

- name: Copie des divers templates.
  template:
    src: templates/chrony.j2
    dest: /etc/chrony.conf
    backup: no
    owner: root
    group: root
    mode: 0644

- name: Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
