---
- name: Installation des dépôts debian.
  template:
    src: templates/sourcelist.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Ajout de dépots tiers.
  template:
    src: "templates/{{ item. source }}"
    dest: "/etc/apt/sources.list.d/{{ item. destination }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - { source: 'backports.j2', destination: 'backports.list' }
    - { source: 'proposedupdate.j2', destination: 'proposedupdate.list' }

- name: Ajout de la résolution du nom du serveur.
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }}  {{ fqdn_machine | lower }} {{ nom | lower }}"
    insertafter: 'EOF'
    state: present
    owner: root
    group: root
    mode: 0644
    backup: no

- name: Mise à jour de la VM.
  apt:
    name: "*"
    state: latest

- name: Suppression d'un package problématique.
  apt:
    name: elpa-magit
    state: absent
    purge: yes

- name: Gestion d'erreur lors de l'installation des packages du role.
  block:
    - name: Installation des packages du rôle.
      apt:
        name: "{{ liste_install }}"
        state: latest
        update_cache: yes
  rescue:
    - name: Suppression d'un package problématique.
      apt:
        name: elpa-magit
        state: absent
        purge: yes

    - name: Installation des packages du rôle.
      apt:
        name: "{{ liste_install }}"
        state: latest
        update_cache: yes

- name: Mise à jour des packages de bases python.
  pip:
    name: "{{ liste_pip }}"
    executable: pip3
    state: latest

- name: Arret de chrony.
  systemd:
    name: chrony
    state: stopped
    enabled: yes

- name: Configuration de la timezone.
  timezone:
    name: Europe/Paris

- name: Copie du script de config de la machine.
  template:
    src: templates/configmachine.j2
    dest: /root/configmachine.sh
    backup: no
    owner: root
    group: root
    mode: 0700

- name: Execution du script de config.
  shell: ./configmachine.sh
  args:
    chdir: /root/
    executable: /bin/bash
  register: var_config
  failed_when: var_config.rc != 0
  changed_when: var_config.rc == 0

- name: Configuration de chrony.
  template:
    src: templates/chrony.j2
    dest: /etc/chrony.conf
    backup: no
    owner: root
    group: root
    mode: 0644

- name: Redémarrage de chrony.
  systemd:
    name: chrony
    state: started
    enabled: yes

- name: Ouverture d'un port pour le service chrony.
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
    immediate: yes

- name: Suppression du script de config.
  file:
    path: /root/configmachine.sh
    state: absent

- name: Configuration du ssh.
  template:
    src: "templates/{{ item.fichier }}"
    dest: "{{ item.chemin }}"
    backup: "{{ item.sauve }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { fichier: 'sshd_config_orig.j2', chemin: '/etc/ssh/sshd_config', sauve: 'no' }
    - { fichier: 'sshd_config_modif.j2', chemin: '/etc/ssh/sshd_config.d/sshd_ansible.conf', sauve: 'no' }

- name: Copie de la banniére.
  copy:
    src: files/motd.txt
    dest: /etc/motd.d/motd
    owner: root
    group: root
    mode: 0644
    backup: no

- name: Activation de la banniére ssh.
  lineinfile:
    path: /etc/ssh/sshd_config.d/sshd_ansible.conf
    regexp: "^#?PrintMotd"
    line: "PrintMotd yes"
    owner: root
    group: root
    mode: 0644
    state: present

- name: Suppression du motd cockpit.
  file:
    path: /etc/motd.d/cockpit
    state: absent

- name: Suppression de la mise à jour du motd.
  file:
    path: /etc/update-motd.d/10-uname
    state: absent

- name: Recharge de la config ssh.
  systemd:
    name: sshd
    state: reloaded
    enabled: yes

- name: Ouverture d'un port pour le service ssh.
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes

- name: Création des répertoires pour les alias.
  file:
    path: "{{ item.chemin }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { chemin: '/root/.alias', mode: '0644' }
    - { chemin: '/etc/skel/.alias', mode: '0755' }

- name: Copie des templates d'alias.
  template:
    src: "templates/{{ item.fichier }}"
    dest: "{{ item.chemin }}"
    backup: "{{ item.sauve }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { fichier: 'alias_utilisateur.j2', chemin: '/etc/skel/.alias/alias.txt', sauve: 'no' }
    - { fichier: 'alias_root.j2', chemin: '/root/.alias/alias.txt', sauve: 'no' }

- name: Ajout d'une référence dans le fichier bashrc.
  lineinfile:
    path: "{{ item }}/.bashrc"
    line: 'source ~/.alias/alias.txt'
    owner: root
    group: root
    mode: 0644
    insertafter: EOF
    state: present
    backup: no
  with_items:
    - /etc/skel
    - /root

- name: Vérification du démarrage de cockpit.
  systemd:
    name: cockpit
    state: started
    enabled: yes

- name: Ouverture d'un port pour le service cockpit.
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled
    immediate: yes

- name: Ouverture d'un port pour les services web.
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - http
    - https

- name: Suppression de l'ancienne clé SSH sur la machine locale.
  shell: 'sed -i "/{{ ansible_default_ipv4.address }}/d" $HOME/.ssh/known_hosts'
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: var_sshkey
  failed_when: var_sshkey.rc != 0
  changed_when: var_sshkey.rc == 0

- name: Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
