---
- name: Création d'un utillisateur.
  hosts: serveur
  remote_user: root
  gather_facts: yes
  vars_prompt:

    - name: login
      prompt: "Veuillez entrer l'identifiant du compte "
      private: no

    - name: password
      prompt: "Veuillez entrer le mot de passe du compte utilisateur "
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
      default: "P@ssW0rD01"

  tasks:
    - name: "Création du compte : {{ login }}"
      user:
        name: "{{ login }}"
        comment: "{{ login }}"
        shell: /bin/bash
        password: "{{ password }}"
        create_home: yes
        state: present
      tags: utils

    - name: "Création du compte sudoer : {{ login }}"
      user:
        name: "{{ login }}"
        comment: "{{ login }}"
        shell: /bin/bash
        password: "{{ password }}"
        create_home: yes
        state: present
        groups: sudo
      tags: admin
