---
- name: Message Discord de début de role.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Démarrage de la migration du système."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Mise à jour du source.list par défaut.
  template:
    src: templates/sourcelisted10.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Installation des packages nécessaire à la migration."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Gestion d'erreur lors de l'installation des packages du role.
  block:
    - name: Installation des packages nécessaire à la migration.
      apt:
        name: "{{ liste_packages_migration }}"
        state: latest
        clean: yes
        update_cache: yes

    - name: Mise à jour de la VM.
      apt:
        name: "*"
        state: latest
  rescue:
    - name: Déblocage du passage à debian 11.
      shell: apt-get update --allow-releaseinfo-change
      args:
        executable: /bin/bash
      register: var_apt
      failed_when: var_apt.rc != 0
      changed_when: var_apt.rc == 0

    - name: Installation des packages nécessaire à la migration.
      apt:
        name: "{{ liste_packages_migration }}"
        state: latest
        clean: yes
        update_cache: yes

    - name: Mise à jour de la VM.
      apt:
        name: "*"
        state: latest

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "ATTENTION !! Le serveur de jeux est en cours de redémarrage."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    embeds:
      - title: "Serveur redémarré avec succès.
        description: |
           "Le serveur a été redémarré avec succès.
           "Tu peux reprendre une vie normale."
           "Et moi, je continue la migration."
        footer:
          text: "Author: Ansible"
        image:
          avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Installation des dépôts debian 11
  template:
    src: templates/sourcelist.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "Mise à jour vers la nouvelle version du système."
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Mise à jour vers debian 11.
  apt:
    force_apt_get: yes
    update_cache: yes
    upgrade: dist

- name: Nettoyage des paquets orphelin.
  apt:
    force_apt_get: yes
    autoremove: yes
    purge: yes

- name: Message Discord intermédiaire.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    content: "ATTENTION !! Le serveur de jeux est en cours de redémarrage. Ben oui pour la 2 ème fois"
    username: Ansible
    avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"

- name: Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Message Discord de fin de role.
  community.general.discord:
    webhook_id: "{{ id_webhook }}"
    webhook_token: "{{ token_webhook }}"
    embeds:
      - title: "Serveur redémarré avec succès.
        description: |
           "Le serveur a été redémarré avec succès.
           "Tu peux reprendre une vie normale."
           "Et moi, je vais me coucher, je suis crevé."
        footer:
          text: "Author: Ansible"
        image:
          avatar_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXv5yLb0EOmi0D9Ca3moLnlNfIqYD2ZYy6-Q&usqp=CAU"
